### ISSUE TITLE
ctrl I is useless - worlds worst editor,interface

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#3]
examples of bugs:
1) misalignment of cursor and text position - a real pain trying to edit. And when pasting from another editor because it's such a pain and never get thru when trying to use the one built in maxima, it puts spaces between every line when pasting and bringing up the file in maxima again and one has to go thru and manually take out all the spaces - though have found an alternate way though - by copying the many lines of code and repasting all in maxima - still one should not have to put up with that.

2)something as simple as
 (n1:1,for n thru 4 do(n:n1,disp(n)))   Not only ctrl I but Nothing not even alt M restart maxima does nothing but have to do ctrl-alt-delete and loose all your work - esp humiliating in cases of long programs

3) Also for:  (n1:1,for n thru 4 do(n:n1:mod(n1,2),disp(n)))
Instead of giving syntax error runs and ctrl i as usual useless and again can't
even restart maxima - have to do ctrl-alt-delete to get out of it. 
Without the disp suppose this type of command is buried within a long program and maxima keeps
forever calculating and one has a very difficult time trying to figure what is wrong.

4) In for example disp("all interparticle potentials which have ") 
it puts question marks at the end for NO reason

5) ASks ridiculous questions already given:
(realonly:true,assume(w^2<1,w>-1,w<1),integrate(integrate(r1^5*exp(-alis[1]*r1^2)*r2^4
*exp(-alis[2]*r2^2),r1,r2*(1-w),inf),r2,0,inf)
+integrate(integrate(r1^5*exp(-alis[1]*r1^2)*r2^4*exp(-alis[2]*r2^2),r1,r2*(1+w),inf),r2,0,inf))

and asks; "is  w^2-2*w+2 pos.,neg. or 0"  and " is  w^2+2*w+2 pos.,neg. or 0 ? "
when that is already obvious from the given  assume(w^2<1,w>-1,w<1)

**Comment by gunterkoenigsmann** [comment]
Nr. 5 isn't caused by wxMaxima but by Maxima which lies at https://maxima.sourceforge.net. The underlying problem is that a truly intelligent assume database would be affected by the halting problem (which means: If you allow it to make too complex decisions it might use indefinite amounts of time. ...but the current assumption database isn't the strongest point of maxima, admittedly.

The Rest I cannot reporduce. Are you using wxMaxima on Windows? If that is true: Would you be willing to try the installer you can find at https://wolfgang.dautermann.at/maxima/nightlybuild/? I guess they have been resolved already. ...or I don't understand the problem.

Thanks in advance,

  Gunter.

**Comment by zmth** [comment]
yes using wxMaxima on windows 7. What do u mean about the installer ? What will that do to what I have already? I may but what does it do ? What problems or issues may it cause? Does it install a new version of maxima? Is there a way i can for " undo " it if desired ?

**Comment by gunterkoenigsmann** [comment]
Yesterday I have accidentally broken the Nightly Build. Which means I hope tomorrow's version will work again. 

If it works again the installer comes with a maxima that also contains all bugfixes that have been written since the last release. I hope if the current problem is solved the new installer will only bring improvements, not problems. If that isn't true feel free to open a ticket at https://github.com/wxMaxima-developers/wxmaxima/issues (If possible please file a separate ticket for every bug which makes resolving one bug at a time easier).

...and you can always uninstall every version of maxima and wxMaxima or install two versions on the same system or (if you want) even tell wxMaxima's configuration dialogue you want to use the maxima from a completely different install. In open-source projects all of these possibilities tend to work just fine and maxima normally is proud that it is up- and downwards-compatible.

**Comment by gunterkoenigsmann** [comment]
Forgot to tell: The current nightly build works again - and contains over a hundred bug fixes.

**Comment by zmth** [comment]
ps: I have been posting bug reports for at least the past 5 years about maxima and have been a member for that long. Now all the sudden about beginning this year I always get the message whenever i post a bug 

" Your post awaits moderator approval "  or something like that and the reason given is post by a    ' non - member '  to a  member only... or to that effect. Why do i get these messages when I AM a member and have been for several years !
 

    On Saturday, March 16, 2019, 7:05:57 AM CDT, Gunter Königsman <notifications@github.com> wrote:  
 
 
Forgot to tell: The current nightly build works again - and contains over a hundred bug fixes.

**Comment by gunterkoenigsmann** [comment]
Nearly everyone gets this message, but the bug tracker still works fine. No idea what causes it but if you want you can ask the maxima-discuss mailing list if they have an idea.

**Comment by doswellf** [comment]
Even a fresh start with wxMaxima 18.02.0 on ubuntu 18.04 will not give a correct result for 

trigsimp(1 + tan(x)^2) 

It just parrots back trigsimp(1+tan(x)^2) instead of 1/cos(x)^2, which is the correct answer.

Yet xmaxima gives a correct result every time for  trigsimp(1 + tan(x)^2): Result is always 1/cos(x)^2

This version of wxMaxima on ubuntu seems to be very sensitive to spaces and starts to break when entry mistakes are made. I have to clear memory and restart maxima, especially if wxMaxima has been running for a long time. 

Lately I've been starting both xmaxima and wxMaxima for older tutorials like Woollett's Maxima By Example. When wxMaxima goes off the rails I try it in xmaxima. Sometimes it's an entry mistake on my part, but often wxMaxima requires a complete restart to get the same results as xmaxima.

Will try to build or get a newer version and report back with the results
Maybe it's just out of date, b

**Comment by doswellf** [comment]
Update on trigsimp(1+tan(x)^2 problem:
If I type in  1+tan(x)^2;  first, hit enter (changed to enter alone for execution) 
then type trigsimp(%)
then I get the correct result 1/cos(x)^2
Shouldn't trigsmp(1+tan(x)^2) on one line work just as well?
I like the wxmaxima interface better, but the console has some strange glitches.

**Comment by doswellf** [comment]
What??? 
After forcing the result with the 2 line solution, now the one line solution is working.
Something seems slightly broken here - again. will try a new version next.

**Comment by gunterkoenigsmann** [comment]
Shift+Space inserts a non-breaking space. Two years ago for a short time there was a big that caused maxima to interpret non-breaking spaces as character, not as space. In current wxMaxima versions this problem should be resolved.

**Comment by doswellf** [comment]
Thanks Gunter! 

That time frame is about right for this version to have that bug. I have to build ncurses6 and some other libs from source to use the 5.42.1 deb packages. If that fails, will build from latest git or tarball.

**Comment by gunterkoenigsmann** [comment]
The latest git version should have many additional help menu and right-click menu items that I hope are helpful => I would recommend that version, currently. Will make a new release once we worked around all the breaking bugs in MacOs.

**Comment by zmth** [comment]
yea i see the later versions do have it so ctrl I does something more of the time but not all the time. Now i have even a worse situation on a file which i thought the newer version would have fixed that even restart maxima won't work and it even takes a long time for ctrl-alt-delete and start task manager to shut down. I did have more of those instances on older version but i see still have atleast this one file on the newer release. Seems all that caused it was float(...) commands to make something run faster but it did anything but that. Can't reload the file either as continuous busy icon and same long time trying to shut it down in task manager and ofcourse lost all my work except for that saved in a backup file which i had to rename the latest default file name. I am attaching the file in case the developers might be able to fix it or see what is the problem.

    On Sunday, April 5, 2020, 11:38:33 PM CDT, Gunter Königsman <notifications@github.com> wrote:  
 
 


The latest git version should have many additional help menu and right-click menu items that I hope are helpful => I would recommend that version, currently. Will make a new release once we worked around all the breaking bugs in MacOs.

**Comment by gunterkoenigsmann** [comment]
That somehow feels like you were running out of RAM. The question now is: Did you run out of RAM, because the problem you were trying to solve was bigger than your RAM - or did you encounter a bug in wxMaxima or a bug in maxima - or in the lisp maxima was compiled by. All of these are possible.
