### ISSUE TITLE
right-mouse button works alike left-mouse button

### ISSUE THREAD

**Issue by msat-cont** [andrejv/wxmaxima#798]
It seems that the commits that solved the assertion failures (ticket #789) introduced an issue that right-mouse button seems to work alike left-mouse button.

1) Open new wxMaxima window, press right-mouse button inside. It used to open "Paste/Select All/..." menu. now it does nothing.

2) Write e.g. 1234, press "Shift" key and move cursor by leftwards button to highlight a part of that 1234 string. Then while still pressing "Shift" key, put mouse pointer on that string and press right-mouse button. It used to open the "cut/copy/paste ..." menu. Now it works alike left-mouse button.

**Comment by gunterkoenigsmann** [comment]
Commit 13d6e9fcc2e9cbfaca0717552475f53479a6d293 should remove the only reason that might hinder the right-click menu from being displayed.

**Comment by gunterkoenigsmann** [comment]
> 1) Open new wxMaxima window, press right-mouse button inside. It used to
> open "Paste/Select All/..." menu. now it does nothing.

Arrgh!

...But I haven't changed anything in this respect?!?

In MathCtrl::OnMouseRightDown (that beginning with line 960 draws the
right-click menu) I only added the following lines:

    if(m_mouseCaptured)
    {
      ReleaseMouse();
      m_mouseCaptured = false;
    }

The only thing these lines do is to inform the operating system that we
don't want to be notified about movements of the mouse cursor if the
worksheet isn't in the mouse focus any more. But on right-clicking it is
in the mouse focus and for drawing the menu we don't need to be notified
about mouse movements: The variable named "event" already contains the
coordinates of the point that was clicked at. And we want to know which
point was clicked at, not which point the mouse cursor was moved to
afterwards.

That means: wxMaxima::SendMaxima can set EnableEdit() to false. Don't
know why this was implemented or if this is needed anymore, though.

The other half of the phenomenon I can describe. At least partially:

The lines

  if (!clickInSelection)
  {
    OnMouseLeftDown(event);

simulate a left mouse click on right-clicking into a selection. Don't
know why this is necessary, neither. My guess would be that the
simulated left click is necessary since it selects a cell... ...and we
need the information which cell is right-clicked at (which after the
left click means: selected) in order to decide which menu items we need
to draw.

On my linux Computer and on a windows Computer I was able to get hold of
the right-click menu works fine.

...but that doesn't mean too much: You seem to be a good software tester
as you found several things I never stumbled upon in months of intensive
use of wxMaxima... ...unfortunately this time I don't have the slightest
idea where the problem lies and since I cannot reproduce it gdb won't
help me finding out where to look...

**Comment by msat-cont** [comment]
It may be just issue on my local install, don't know. I've found that commenting out the line 972 at MathCtrl.cpp
```
this->Disconnect(wxEVT_MOTION,wxMouseEventHandler(MathCtrl::OnMouseMotion));
```
brings back the necessity-for-click-doubling issue together with assertion failures; and alike when I put *and false* into the if *if(m_mouseCaptured)* at the 969 line there (i.e. disabling the whole 969-974 branch). Then I have the right-click menu back, but with severe issues.

If I disable the whole branch (for "emulate a left click to set the cursor") starting from line 964, like putting *and false* there
```
  if (!clickInSelection and false)
```
it seems to work *nearly* correctly for me then. As you wrote, a wrong menu is printed there though if the cell was not already selected.

**Comment by gunterkoenigsmann** [comment]
I would tend to blame a bug in wxWidgets for this. But perhaps I've found a way to avoid it. Let's hope that the commit I've just pushed resolves this issue once and for all.

**Comment by msat-cont** [comment]
I forgot to add that the right-mouse-button menu tends to appear after some (random) amount of right-mouse-clicks, commonly like 10-20, sometimes earlier, sometimes not at all. It indeed suggests some wxWidgets issue (though the 15.08.2 wxMaxima version is not affected by that).

I've just pulled/compiled the latest githead version, but the issue remains there. One thing that is interesting though (found it just now) is the next case:
* open new wxMaxima worksheet,
* write e.g. 12345 and click enter to make a 12345 output line,
* clicking right-mouse button to the output line makes that line selected and highlighted,
* waiting a bit (like half a second), and clicking again by right-mouse button brings (the right) menu here.

I.e. the output lines are affected the least here (needing a second click; or a third click if not waiting).

**Comment by gunterkoenigsmann** [comment]
I have now experimentally added a redraw action before popping up the menu. But - as on all computers I have access to this problem doesn't appear I am completely lost what might cause the problem. To me it nearly looks like OnMouseLeftDown() if called by OnMouseRightDown() tends not to select items.

**Comment by gunterkoenigsmann** [comment]
In the meantime I have revised the selection code => Closing this issue as it will be resolved in the upcoming release.
